#!/bin/bash
# Quick script to update webhook secret on server

echo "🔧 Updating Stripe Webhook Secret on Server"
echo "=============================================="
echo ""
echo "Run these commands on your SERVER via SSH:"
echo ""
echo "cd /root/DomainSeller-Backend"
echo ""
echo "# Update webhook secret"
echo "sed -i 's/STRIPE_WEBHOOK_SECRET=whsec_YCHggf8PxJtARxcFmBvdYMuWnGZwuscb/STRIPE_WEBHOOK_SECRET=whsec_jZ3qbImyaOeZsojRF7jE6N2crAfbeKkz/' .env"
echo ""
echo "# Verify the change"
echo "grep STRIPE_WEBHOOK_SECRET .env"
echo ""
echo "# Restart server"
echo "pm2 restart node-bac"
echo ""
echo "# Watch logs"
echo "pm2 logs node-bac --lines 50"
echo ""
echo "=============================================="
echo "✅ After running these commands, test with a real payment!"

