-- Table for storing email conversations with buyers
CREATE TABLE IF NOT EXISTS email_conversations (
  id SERIAL PRIMARY KEY,
  campaign_id VARCHAR(255) NOT NULL,
  buyer_email VARCHAR(255) NOT NULL,
  buyer_name VARCHAR(255),
  direction VARCHAR(20) NOT NULL CHECK (direction IN ('inbound', 'outbound')),
  subject TEXT,
  message_content TEXT NOT NULL,
  received_at TIMESTAMP DEFAULT NOW(),
  user_id INTEGER,
  domain_name VARCHAR(255),
  ai_generated BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT NOW(),
  
  FOREIGN KEY (campaign_id) REFERENCES campaigns(campaign_id) ON DELETE CASCADE
);

-- Index for faster lookups
CREATE INDEX IF NOT EXISTS idx_conversations_campaign ON email_conversations(campaign_id);
CREATE INDEX IF NOT EXISTS idx_conversations_buyer ON email_conversations(buyer_email);
CREATE INDEX IF NOT EXISTS idx_conversations_direction ON email_conversations(direction);
CREATE INDEX IF NOT EXISTS idx_conversations_received ON email_conversations(received_at DESC);

-- Comments
COMMENT ON TABLE email_conversations IS 'Stores all email conversations between sellers and buyers';
COMMENT ON COLUMN email_conversations.direction IS 'inbound = buyer to seller, outbound = seller to buyer';
COMMENT ON COLUMN email_conversations.ai_generated IS 'TRUE if this message was generated by AI agent';

